paths:
    diffusers_models_path: /mnt/sd/diffusers-models
    ckpt_models_path: /mnt/sd/ckpt-models
    training_images_path: /mnt/sd/training-images
    class_images_path: /mnt/sd/class-images

jobs:
    job1:
        job_paths:
            training_model: sd-v1-4
            output_name: test-advanced
            class_images: test-10
            training_images: 1-img-test
        train_config:
            instance_prompt: "sé person"
            class_prompt: "person"
            num_class_images: 10
            max_train_steps: 20
            save_every_n_steps: 5
            min_save_step: 10
            train_text_encoder:
            gradient_accumulation_steps: 1
            mixed_precision: fp16
            seed: 80085
            train_batch_size: 2
            learning_rate: 2e-6
            lr_warmup_steps: 0
            sample_batch_size: 4
            use_8bit_adam:
            with_prior_preservation:
            prior_loss_weight: 1
            gradient_checkpointing:
        post_config:
            convert_to_ckpt: true
            prune: true
            ckpt_only: true
