paths:
    diffusers_models_path: /mnt/sd/diffusers-models
    ckpt_models_path: /mnt/sd/ckpt-models
    training_images_path: /mnt/sd/training-images

jobs:
    job1:
        job_paths:
            training_model: sd-v1-4
            output_name: test-simple
            training_images: 1-img-test
        train_config:
            instance_prompt: "sé person"
            mixed_precision: fp16
            seed: 80085
            train_batch_size: 1
            max_train_steps: 25
        post_config:
            convert_to_ckpt: true
            ckpt_only: true
            prune: true
