paths:
    diffusers_models_path: /mnt/sd/diffusers-models
    ckpt_models_path: /mnt/sd/ckpt-models
    training_images_path: /mnt/sd/training-images
    class_images_path: /mnt/sd/class-images

jobs:
    job1:
        job_paths:
            output_name: test-advanced   # Name of the model which will be used for output diffusers models and ckpt models
            training_model: sd-v1-4      # A diffusers model which is located in your diffusers model path
            training_images: 1-img-test  # Name of a folder inside your training_images_path
            class_images: test-10        # Name of a folder inside your class_images_path
        train_config:
            instance_prompt: "sé person"
            class_prompt: "person"
            num_class_images: 10
            max_train_steps: 20
            save_interval: 5
            save_min_steps: 10
            train_text_encoder:
            gradient_accumulation_steps: 1
            mixed_precision: fp16
            seed: 80085
            train_batch_size: 2
            learning_rate: 2e-6
            lr_warmup_steps: 0
            sample_batch_size: 4
            prior_loss_weight: 1
            use_8bit_adam:
            with_prior_preservation:
            gradient_checkpointing:
        post_config:
            convert_to_ckpt: true       # Convert from diffusers model into a ckpt file
            ckpt_only: true             # Delete the diffusers model after conversion
            prune: true                 # Prune the created ckpt model
